source "$HOME/.dotfiles/bash_zsh/env_vars.sh"

# start fish
#   - checks if the parent process (PPID) is not fish. This prevents the script from executing fish when you're already in a fish shell
#   - checks if the shell was not started with a command string, like bash -c command
#   - checks if fish is available on the system
if [[ $(ps --no-header --pid=$PPID --format=comm) != "fish" && -z ${BASH_EXECUTION_STRING} && $(command -v fish) ]]
then
    shopt -q login_shell && LOGIN_OPTION='--login' || LOGIN_OPTION=''
    exec fish $LOGIN_OPTION
fi

# if fish is not available, then proceed with bash config

export SHELL="/usr/bin/bash"
export HISTFILE="$HOME/.bash_history"  # history filepath
export HISTSIZE=10000  # maximum events for internal history
export HISTFILESIZE=20000  # maximum events for internal history
export HISTCONTROL=ignoreboth:erasedups  # dont write a duplicate event to the history file
export HISTIGNORE="ls:bg:fg:exit:reset:clear"
shopt -s autocd  # cd then entering just path
shopt -s histappend  # append to the history file, don't overwrite it
shopt -s histverify  # dont execute history selection

PS1='\e[32m\u@\h:\e[34m\W \e[31m>\e[0m '  # prompt

set -o vi  # vi mode
bind -m vi-command 'Control-l: clear-screen'
bind -m vi-insert 'Control-l: clear-screen'

# edit command in nvim by pressing <C-e> in normal mode
source "$HOME/.dotfiles/bash_zsh/edit_command.sh"
bind -x '"\C-e": edit_command_line'

# fzf
source /usr/share/fzf/key-bindings.bash
source /usr/share/fzf/completion.bash
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'

# nn cd on quit
source "$HOME/.dotfiles/bash_zsh/nnn_cd_on_quit.sh"

# aliases
source "$HOME/.dotfiles/bash_zsh/aliases.sh"
